### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by MeNoFade** [MarmoriPelaa/GTPackCap#1]
After starting the program, it displays the word "Initialized", I go into the Grootopia and nothing happens, just the files stm_auto, stm_client, stm_server are empty. Help!

**Comment by MarmoriPelaa** [comment]
You have to use a hosts file to redirect growtopia1.com to 127.0.0.1
Make sure you are on windows and put the hosts file into
```C:\Windows\System32\drivers\etc```

The required files are now available for download. Sorry for the inconvenience! I was in a rush while making this. If you have any further questions, leave them in this issue. If not, please close this issue.

**Comment by MeNoFade** [comment]
Thank you!
