### ISSUE TITLE
OnSendToServer bug. 

### ISSUE THREAD

**Issue by MeNoFade** [MarmoriPelaa/GTPackCap#3]
Hello. I have bug with OnSendToServer. When the growtopia sends a redirect to another server, when I'm in the game (for example, if the world is on another server), then this disconnects from the gt server. Is it possible to fix this?
![image](https://user-images.githubusercontent.com/44878241/71666128-b1280b00-2d70-11ea-8e8b-47ccd745aff7.png)

**Comment by MarmoriPelaa** [comment]
OnSendToServer is a bit buggy at the moment. I have tried to fix this by saving the redirect packet login token and user id. Apparently the loginToken is not being set for you. I haven't tested this in version 3.000 so I'll look into it. For now I would just try logging in again and then seeing if it works.

**Comment by iProgramMC** [comment]
@MarmoriPelaa there was a bug in my client where the LMode was not properly checked. If it is 1 then the userID/token should be used, otherwise not. (It's at index 5)

**Comment by iProgramMC** [comment]
Otherwise, nice proxy!

**Comment by MeNoFade** [comment]
@iProgramMC I did a lmode check, but I still get stuck when connecting or entering the world with token -1. Do not know how to fix it?

**Comment by MeNoFade** [comment]
Fixed!

**Comment by MeNoFade** [comment]
Fixed!

**Comment by MarmoriPelaa** [comment]
Lmao you guys are better at this than me.. Would you mind making a PR?
