### ISSUE TITLE
compiler error: C4703

### ISSUE THREAD

**Issue by atomiclucky** [MarmoriPelaa/GTPackCap#7]
![paveikslas](https://user-images.githubusercontent.com/49339987/74085582-ff70ae00-4a82-11ea-8e05-85a6ba085340.png)
Tried setting it to null, but got a bunch of more errors

**Comment by MoanHawks** [comment]
try edit to event.peer

**Comment by atomiclucky** [comment]
thanks! also had to compile the library myself

**Comment by atomiclucky** [comment]
oh i shouldn't be thanking in advance. If I just change it to event.peer, I'll get the client peer, not the server peer

**Comment by atomiclucky** [comment]
thanks! also had to compile the library myself

**Comment by atomiclucky** [comment]
fixed

**Comment by zix3r** [comment]
I have the same problem, please tell me how you fixed it.
